language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer run test

notifications:
  email:
    on_success: never
    on_failuer: always
